apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
    namespace: vikunja
stringData:
    VIKUNJA_REDIS_PASSWORD: ENC[AES256_GCM,data:vvi4EiX1fv12Le4bDQ==,iv:5qfmk6znuFPdqwQEu4TrKSrdclxOnBgMfYqKATes/Fo=,tag:3A88bHDthr92JIHWW9vkPg==,type:str]
    VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:7R8K1VFFjR6X5IIPSXjRlw==,iv:6hB3Gi48/sEzvvqnQNfQJ2lqc+nzXt9flqA61g2KNak=,tag:kRJcCY5ujy52kxTpcMp75Q==,type:str]
    VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:BTibRhfrsNRrag30UeebVp4wEYho8b1+zf7WRIEAEG29fDVt96Z62DVrzI9/jrFJP/YEsdBe2s2w66WLcHDEeBgvb9zSaY1d6H4D2YsTPyzQh4W35Vw9noK4RFjom6hDXfum98+c6W4u/jQKRa/7iM0vEx6aINU2mHUaiEbNtXaMH6u6Kdzwhoj6QlCWqNrJZFGamTe3zsdCvqfN7RQ2fY79tgVIx3VUC6Hk5i/LfgM7r+RA+uQdBbXTbg==,iv:Cm3iU6DGgwOsuoJT/0It9hrKoGfSusNllz6vxPsJ7Q4=,tag:pdyrHDD2xXyuF32OYCMuNw==,type:str]
    VIKUNJA_MAILER_HOST: ENC[AES256_GCM,data:11zuLuIJn+NVAg39fc858nI=,iv:QKu5VHPIwxzpSYGyCVQ8/LCK4iGt3D3Zbfr47DdUgoA=,tag:scK8Z05xR2c+2vF3BvZJYQ==,type:str]
    VIKUNJA_MAILER_PORT: ENC[AES256_GCM,data:/MAU,iv:ooZB0IU2/U2Di9+mCnbxJu+jP6JEaLGijkSUhvB7lmE=,tag:1j41yb1KozZrOwXtHwoFiQ==,type:str]
    VIKUNJA_MAILER_AUTHTYPE: ENC[AES256_GCM,data:5mRfl88=,iv:upLWw85pYalmBCX5TPBTKZ1tKXRkGsyIiN44+kiqScc=,tag:Y/u0lNcHZf1NexAUvyrAWw==,type:str]
    VIKUNJA_MAILER_USERNAME: ENC[AES256_GCM,data:zar1ty/SwqvtLZA3W9ZLJIaRIlJBJsDV/ah1gNZEsz0=,iv:GSbaYXfF58NMna/PuP7bJ0YCaUHENxG58kxXBuPDJ70=,tag:8j/cABmJJNoQiiXQVHOWBg==,type:str]
    VIKUNJA_MAILER_PASSWORD: ENC[AES256_GCM,data:wEDecJrnG/N54sYiIcfvBT/GT0EfGhEqFExqeil7JLQ=,iv:dcqYBid+dkn+Ud3SGtZ2bLETpn/DlHTXZszRGYd47gg=,tag:9s6f0pLHitCTIL0byNsiLA==,type:str]
    VIKUNJA_MAILER_FROMEMAIL: ENC[AES256_GCM,data:AE/xskhWR41WTMx8,iv:raGxyo2v9pnM8YNqo6bD3FeXMvYFJO4gOK2IY12corc=,tag:BY5BcErOKsgoCAS8pbVkWQ==,type:str]
    VIKUNJA_METRICS_USERNAME: ENC[AES256_GCM,data:2nRkHP+m,iv:8xO8y4nMuh4Dyc43/EG4TueEMYSVJmBhzv2opfqvI8w=,tag:WfcMAuilvM9QFLvmYjaDbQ==,type:str]
    VIKUNJA_METRICS_PASSWORD: ENC[AES256_GCM,data:gOOkMxyJhUnW4/uarmpdiAJaV2tMImyFrbIjHQ==,iv:t1ewgiDAZnU5X1SgtSag05dU/6PUqcJwbhmmavzgRMo=,tag:VeUga+QVYohL0E4kMKeGuw==,type:str]
    #ENC[AES256_GCM,data:ED5mOiMA9JSDRKnwF8Gk/9PRdfaF9YMclyUXYDGXpvbb/xPca+PYHC7rsMRBWgGbjXa27zGfZ1yMUzcyGNdWvk2nVBrLHW3j6BVSFuvx8D/OdIN7Qxp+t1qa4w==,iv:PKyPLqXEZv4JuQnCPKefMnBbpszdiL6xRivuBUIidJk=,tag:cLMFc+GZoIZzqlV4EtQTOw==,type:comment]
    #ENC[AES256_GCM,data:FAr3r5KHfDRswHOiH0o4pYrbxW8qASR4iRmZUGzaDtGYWLPQIkrKr4SSaVgCrjG5zXuEZbH0kYPF/xN1LNDLO3rms47m8+gLg1NRA/+HZJysy3Zsyi8RQOETZA0qR26BM0HrezBPhMzuAUNkrfeQzvdkQ8oc7dHMuSVkIQnaQCwIfEmSMFDDnctxQHiycAYHeI4EOw1k4K3hHi4AWa5w7LfCM1Aao7Rk+Y6U3AnfZBphAWzGmPN3,iv:Qdc+4KJjq94ZevnlCxQDdqpFve/B2RLKI8t7hzR0JN8=,tag:dVYB8vVG1nR4XkgJL2r5VA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMWh2cVRETW1ETHZodzBT
            dzdDSGdxZXdScUNCbytaTCtTWU5EZjRKT0VFCjZnUWpyVVRVOEpWNnp6T21QYlAv
            TTN1VHc4K0FpeDNkUEJRclVFcWxINmMKLS0tIHgyWTN6RG5hUHAzK3QxbDJiRUQ5
            TEdNbk1veWg5N1AwYitqNjR6THdFR1EKz1wcIerYXEOWhTptxrf/19YwWjOrPMWG
            SsBnaNFd6xooFfAzGfy8iogy7bLf0/Yam4BHqUHWRjvbkn0gkRxIvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-14T11:40:23Z"
    mac: ENC[AES256_GCM,data:O1BEVmuR2gylBqGU34CZdb8YoW+S9n65pWrDY59dmO/xBaVDEgBYB0NX5jzzuypLaB2biwvg+ykOMUjGcI5j6olAtU85vqmss4lfau6tfu9ChvYVoO0y0ZMit1QXEnTnnV9DQ+mln2lIa/Dmos4Rmo9l91MzMv+/8pE6djeXRE4=,iv:3hwcvTAq+Ml87iS2viSBfVJPJKWYn/6zujWRbaSAgIE=,tag:uWeY3BwVSr2Mb14eENxo3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: eed4fb6a16dc6addd47553c3020798d81a4773f21667dd8cdc776ece3fbf7a70
