kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: dbbackup-secret
    namespace: backup
stringData:
    DEFAULT_S3_KEY_SECRET: ENC[AES256_GCM,data:YKPpwym3DJZEYB/GmpVa5PNHYZwzY2ags0Ukv7sXBZlJNlh74JV+Q9g1Rgcx3CUV,iv:Blb2ot/WWCfctvfBjRU0gcm+ym85mtM95L8LDeaOkzI=,tag:s/jjaqv6hf3F/4m4YDxUCg==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:caTdAyav+9HEBYbYfA==,iv:rCxacl8uQwWn1rAdIU337fxgYsanhYw55+1Qu//aoFc=,tag:3JYE+x2eMe3zlRG2U5Q86w==,type:str]
    MAIL_TO: ENC[AES256_GCM,data:4MjUREPCj/YfyyUsESq35RdJnU2QEbY=,iv:64tZw2xFo1hd+05KIEPw/oDdXjxNbhGnSZ3EsoY1sRA=,tag:WI1duP887ZZsyTUMbsZcrQ==,type:str]
    DB01_PASS: ENC[AES256_GCM,data:xbRAeepBRYCfZj3UZ6/rmvzvJ7vgkw==,iv:2P9Hr+98lqkyF5W1i9OL8GiHgC/pY8/4GBCUxvGIXeY=,tag:nS7Bk/PnqfGV8xx4ssS9mA==,type:str]
    DB02_PASS: ENC[AES256_GCM,data:8gd5cidP6nT+VWjTki+T5jSeV9h3eQpm3gE=,iv:GKfLfGXIwngKSC7E3K8DTWclWxliypcTsL905X6h8qw=,tag:1Isls7Do1MbXkdY1p4Eb4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6amxIeTllRDlTd3ZTbSty
            Q0NwdFJuc08xelhYT0ZQNEdTL3FxZmc1ZzI4CnVYdXkrelNUZ2YxY0VyQjhFV0t5
            ZWZGMUF0Qjhyb0VkSE5wdS9XMThnV3MKLS0tIHZYZTc3dTVndHVhNGxqL1MwdEY4
            am1obEZjS2U4ZUtBMnFlamZpdSt1Q3MKtMI2Y2ZsvmFjobUOaRVIr1mtxm8ZJaIi
            K+nq8Rnj50jC5CfwTKxQKBUI431G+OnQCJOTS9MEjPAJ3X6dISCOhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-14T13:09:58Z"
    mac: ENC[AES256_GCM,data:AMaIZSNPivDvce7Bt2FLEdlpt8LVlKFB+6FO9HfkHCtEUT65r3m8b3REuyjGemrT4YJlukGqWjOnc/WA70LpH5bMwO/GfwwLBO0GV/2z5kZazsTs+Y8dgKyW46DJlnU4Y3J6wB/7V5yJ4SqQdsr/Q8pz998HZEJe/AP2Tx2+shU=,iv:koJwAFW67hCcdugrhYVWxajBA3v+vcBm2uANhFJlxWw=,tag:GbAgRYxBTdpPXly1wWspvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: 9a85feb06d5ec56d9fb0b4b47c89ae6768c1362150baad1e3f21767898037dee
