kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: redis-secret
    namespace: redis
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:vuhIYD+u1c1iwrO6rQ==,iv:Y1hxHYWN3K2OzeM67ZQMo7Ce/tPzND1Bo2KDbYcGPxk=,tag:mlrmNWXyFSA0nZbb9mK7ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TUpPMERxVE1GbDlFSjZp
            bmlSVDJYTjZ1eFpBejFYVG4ydGQ1Qk0yNWpRCkJaeDU4YVpJZUZqMEhTaFF3K3Rv
            WnZRTGdab2F4K2x2bUlwNHp5R1RkNTAKLS0tIGwwdVpEblMrZC9BWjNaemxVYjRM
            RGdTWHFobEU4VnJzSURKWENPNDZHRlkKJJuCw0tJf9OTxdJ/Brn2CACKK3l+id8w
            Qwspd00rCOt5dt2VIRatVC8L41e3yihvPE27QQ3HWSHG7bkzvnQd/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-14T15:02:11Z"
    mac: ENC[AES256_GCM,data:mUq+lRlKwy64ObKGmpPO+tYY5U8ZbY8cBpFxxKk82sm/WGWiV48WMEg/Z2BTyP+nxyhEQDT6c7qu5zU37oCF6N8kmlqxmNp2p6trXbY8tImAcNR1MwTrQt3uhbQvRJKM3i1FJxy4tWmio1byeDX6jLFNbzgFmBZvrkjGhFdGhYA=,iv:CKAoRmmTel4VYjowb/FmiOzjp/X7WVwYGPQPFEstX3o=,tag:8Ou59bPjSCfQmZloRmjDDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: a3202c02ad984efd3b4b6c2be3f16121a5f44b36bfe30cd971c4b53aece1a469
