apiVersion: v1
kind: Secret
metadata:
    name: traefik-providers-secret
    namespace: traefik
stringData:
    example.yaml: |-
        http:
          routers:
            example:
              entryPoints:
                - "websecure"
              rule: "Host (`subdomain.f9.casa`)"
              tls:
              service: example
              middlewares: authentik-authentik@kubernetescrd # Comment to skip using Authentik

          services:
            example:
              loadBalancer:
                servers:
                  - url: "http://123.123.123.123:80"