apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 34.1.0
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: traefik
  valuesFrom:
    - kind: ConfigMap
      name: traefik-config