kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: authentik-secret
    namespace: authentik
    annotations: 
      kustomize.toolkit.fluxcd.io/reconcile: disabled
stringData:
    AUTHENTIK_POSTGRESQL__PASSWORD: "[AUTHENTIK_POSTGRESQL__PASSWORD]"
    AUTHENTIK_REDIS__PASSWORD: "[AUTHENTIK_REDIS__PASSWORD]"
    AUTHENTIK_SECRET_KEY: "[AUTHENTIK_SECRET_KEY]"
    TEST: "[AUTHENTIK_SECRET_KEY]"