kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mirror-to-gitea-secret
    namespace: git
stringData:
    GITEA_TOKEN: ENC[AES256_GCM,data:dks8E3z0symHTnt7N5DNVqXhJ0G4b3CyjFSdMoUVPJShB8KokGXCRQ==,iv:zKLcaCpxQvmlSJDPCE/dEWFxe5xTURWlAuFYhWr54yM=,tag:9qe1lzg2VgpYkwE1Nj0aig==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:WKurMlm+TPlnPZnHBj2VKjiIoIz8gCFYpFHDC3aq+cs/k8tK9QXFFQ==,iv:URIF2mseva2F6qvASZTcR10fSM5CPD2Uy/1mJc6NUCM=,tag:UU6+MgluDI3ZjDhp3uJWgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNmpHWWkyd1N3K2FHdGhz
            OXRRRFk2LzVLeFdkL0VKZW1kdm1DVTdrTG5jCkJVNEpHYjdpdjF1ZnpCdGtDazh4
            WUJnQ0hLeFBzM0hudXBHc2hwRTRtc1EKLS0tIG81T3hlbllmeHd0UlFjay9EczVp
            WnU5dzNZalV4SlkzdzljcTVYcXVLeG8Kfk6xX7fU1AaeVAtahs0voxTLjBLpwkQI
            r6VUDDKtDxf/Dgsy8oSzzy4cN9+blh0gVoE9iOG2/G9xxUEMCOxCaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-20T09:52:15Z"
    mac: ENC[AES256_GCM,data:j+u6e40H7BPeaT8Nrskbh3yuOMKQn+U7bh6Z0qUBpp/MyNCoz5FNZJ9gLepThp74fxKECLEVRVJhuVp8Jy1WkVoN95fnZeP03n259E2RA2ff/hBqD+WfOXrG+csZbyo9I46+qyZNhvmfQV/pc1gkIh/lZvVZHCTTftMp5Mne9eQ=,iv:KeLCudNF3auBKGGt/mVdF+1DVcpaz9lmVYzd6msRv5Q=,tag:xCGQ5l1m0X0STlHLCk/O8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: 799cbdb36871623e137f2a19f3f1dae1fda821cf79cc4d674c91f07749fc2b0e
