apiVersion: v1
kind: Secret
metadata:
    name: debtmanager-secret
    namespace: webdev
stringData:
    DB_PASS: ENC[AES256_GCM,data:9KUWjE58tlv7DHsyRRADng==,iv:AvDTKZ7SpccW92H0TYvdnDEKKCdxA+aAIqo9YLZSiyk=,tag:A2pCaQ1UYL2d0dZxblOaHw==,type:str]
    STARLING_WEBHOOK_SECRET: ENC[AES256_GCM,data:taqq4f8wzub8RDEa9WfqhQsOcXCgYyCkQwLdgyQQ4/W1GLe3ZqFpz7vEn82oWRSvRTfOT+rDxAt0MrHx3FTjKSEXCDo8SPKoT7taZypPv5HiANNVCKOKHbVGVUVslgtjlk2n4t2u3D+O5EaKrT8AroXyDf4iVDWsmwm9sB16Wrj3Jpxsj4FQbv4lD9dFX6H3hTnHaTtiwVq5DuQpAbHJQiZZwUElxqEf4GHuykU0gZyO3rE0TuSXBV+JK+pW/ri5UGMC5MVQ27ZxyRtmQDt9NPUmuu3Q6iicIbiKc94H303JVoCsOfCeZaHYOh+PYrLi9JMshH04TboL7MvP++/04Q+U3g7HM/qKNZ7HiQjj4YCuHmjw8HZoZyVZG/ndAFf0ZZ54IzPnXeKBcHwgRXnPUD+mLC+vaTUp2DrG3DkDOBE6dc+6FSbYJ4Gd3ntgQ7I2X03koNqdWlK8JYogYOg0jpmSEXoJxpwIGY6XdnrNTBYT7CoA01MIH1MeppaNKkRyHl3AiSOZaW8=,iv:E2R9hIZUasGIT41vVJAKkwC2i54SAuzUcVhtXWbwt0Y=,tag:kBtJNAMDzbTdtBPill/gYg==,type:str]
    DISCORD_CLIENT_ID: ENC[AES256_GCM,data:k0VijoMeXKyNcfM4HeY3Sgky1Q==,iv:FV/FTkQToUuGoT2R8PZoZfti9zhxFEfDfF2w/7PhoQE=,tag:65vxd+j9d1RjGD8WWDi/SQ==,type:str]
    DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:mkwG5ecuEcHOnbYDDEpaE1xO5lyA3e0ziP47ZuVL6cY=,iv:SXbQrobRXVu1bQIpA7a75ieo1wYnxsc26L6+A2aFC0M=,tag:4dUxTk8SHHtEyS6abm890w==,type:str]
    DISCORD_ADMIN: ENC[AES256_GCM,data:QXqIgvTYbETaQ1g0fZ061y9H,iv:H4mEM4p5zcPKrcMrfS1dlXhuk7k0Xl8YQuuFzG22i9U=,tag:yI++/Ln2ATtUeP0gEMlR9A==,type:str]
    DISCORD_WEBHOOK: ENC[AES256_GCM,data:n0iCedJuFoOMc3swPgIgS4pO2rZ/lGMYS17MOhNnwu2JrM0TqPp/3EG5kzvkjBM/g4VhB2VTNFqbOLRYb+swYFW0rXLCOOnq9+dhR5hzbBjAuCnezEwBD9d6CUf6mLLysUxbczEvtfslPi0dYBsa98KXITulIjYgXv29,iv:td71GUxP8YaY0nAF56r4Uye99o7QXXnTDAQeUxR+p6o=,tag:nx3tJOtOJXULqz6MQ9SVmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMXZDVFovMUpTTFdoMnZh
            Um1OTmJSN2J5WThpZk11enJIL2tIL3A1eDFJCk9mNFROb2pldkxNSXpQYmJhbDRW
            NEhJa1BTM3FGMWJ4UEdpNHVJWWtJdWsKLS0tIGlIeWw0Z0VGSzFKMnR2OTNVdGxL
            K1piTEdXaFNlUFY5aXdVNHc2SmZ1eVkKX10zpEGYcNB6Vy5n26vVXTIoXOQN3VCx
            7VSukTwaYqhAQxOecXs7YlFtAEpzMdVTqDvFWv74KGroGIp7nnWP6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-21T19:01:28Z"
    mac: ENC[AES256_GCM,data:lCCTOzZ18xI46gDoEOigLNZEKPFMzAygzWkByF2hrIvHaZBtpYzB61+bOvhEfUsLDbkA6w2W911QrzOMlTFbw3DasWWQU+7OYIJxCYe+TprnEF1HuvTmbUf6VE8RvU6HPdny++e3SO0qDcoW4+QgMPoDVGSdpZS1ef6tQiTM85g=,iv:qAyoeaUja+UiaAHdNJ4GqXIsA7UV7dmbBpmh/K5n+Uw=,tag:geyL3vW8UtDXRyUeOQutLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: 161736f5acd9ad5f450a523812cfb9fb0589642b0e4629f4d01342b8664095b4
