kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: homepage-secret
    namespace: homepage
stringData:
    HOMEPAGE_VAR_OPENWRT_URL: ENC[AES256_GCM,data:vJjmUc0e0dwKzPKxFSUFwFZO,iv:7xSY3st/mKaVvcwgFXDCyeTPNoMXcH7Lk/nay3ekcnA=,tag:JcJ3p/ucNKXwBzWuP4+IhQ==,type:str]
    HOMEPAGE_VAR_OPENWRT_USERNAME: ENC[AES256_GCM,data:SxTNPKDPdck=,iv:E6B5as3H0L9XuR+5dKJ7zpgn36RO3spnPRcc0IAc7TQ=,tag:EeJloNbMDJLOEgtXXYKSXg==,type:str]
    HOMEPAGE_VAR_OPENWRT_PASSWORD: ENC[AES256_GCM,data:uQ1lzRZD1TY=,iv:mikL4TXMavRx0t14bwFcy0mlGAWrt81YPm3fLlk38w4=,tag:ZKwb46uyC6Hu8prv2DfFDw==,type:str]
    HOMEPAGE_VAR_ADGUARD_URL: ENC[AES256_GCM,data:H7ctSXSjbma4UKwwz+I/hppJvrOdVlU=,iv:0dudHOxRP9X5FRyfVemvq0I8QBJRf9fPykjf5zfBVvU=,tag:e6sk5R9noyma7MZVjyU62A==,type:str]
    HOMEPAGE_VAR_ADGUARD_USERNAME: ENC[AES256_GCM,data:YJaJ39Q=,iv:9D1IMZnMeoew+QTVEzlynq8A/EqhdRW3zxJKwuhhmoQ=,tag:ysI8pI1neEumUEKWEe25pg==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:m1e8wKNV/74=,iv:fn5G70+tnh+WUsKRCFEY6TvdFw6Gr6QUWo5KCwXZZnY=,tag:PtRGu1dTs9QrV/e5TYxHgQ==,type:str]
    HOMEPAGE_VAR_ADGUARD_HREF: ENC[AES256_GCM,data:bWGr+ilV7M0GVbR8NnT4V07+Bm4JX+4=,iv:OXBuuX/kOl3MYz5QjKvm7mHJdivo2WH51UF/pfGIuu4=,tag:mk0cSowpsoZaI2oJFiJWKA==,type:str]
    HOMEPAGE_VAR_PROXMOX1_URL: ENC[AES256_GCM,data:zsCpH6/3V03uA4A/b4Eg2rNoPgXwYw==,iv:Ib4RsXM31kxahRe0ASRXMVNIyyyn/e2S3B83SaO7SGs=,tag:dlL2xQiIqZFN7KTLkbh1UA==,type:str]
    HOMEPAGE_VAR_PROXMOX2_URL: ENC[AES256_GCM,data:7M4yej+rYP12F3aYcNZ9ZSrpbIVF/A==,iv:XIUorsB/Y4gMMS+ovfjfOakWW9OWwRiqSQUgonBuR4w=,tag:2CUosKk2TF5it5Rg/Gp8ow==,type:str]
    HOMEPAGE_VAR_PROXMOX3_URL: ENC[AES256_GCM,data:NM6KWwYd6rkT1dblHrgurJHZdKTZow==,iv:CfDXJUzmpy49b/Fyh09P047UV7mC84tc+WW1Sb8o7DA=,tag:Qosz6+iay8B8l05wCe10YA==,type:str]
    HOMEPAGE_VAR_PROXMOX_USERNAME: ENC[AES256_GCM,data:wmNb6eFcAyIjoKubZtuBtQ==,iv:TwPfWgOu9fToUj3QrgwlDcjinjYfBS4Nf0oqfS86uyM=,tag:0fclXLEQ+GnFQDX58h/S3A==,type:str]
    HOMEPAGE_VAR_PROXMOX_PASSWORD: ENC[AES256_GCM,data:uJpANShhbzfjoI0ynm6rr1ZXwJ5c767NFrJ3YSURmBCMTWkw,iv:IZCH8IQDE0ZEU8/z5hPYKXqESfHvN96vsDtvnoROfT0=,tag:ZMGQ/K7blKkTKCPjzL9ggA==,type:str]
    HOMEPAGE_VAR_DELUGE_URL: ENC[AES256_GCM,data:C1tbutassg2mXHquwQuu1ANjgdjFZtY=,iv:czDMf9Jy8r/RFC1RNNb4sfaSvlexAF9C2tStLXl4I48=,tag:9jpt80jfQ30mwGW357NVgg==,type:str]
    HOMEPAGE_VAR_DELUGE_PASSWORD: ""
    HOMEPAGE_VAR_DELUGE_HREF: ENC[AES256_GCM,data:ZepW7J33jJ3lem03OBGXrgTmILeHeQ+e,iv:2kfJ5qK15P1bOI3/jHho7E80EmxwtxXBBs9FUIeowXI=,tag:Yf+uP1WIehOyhYtqba43ew==,type:str]
    HOMEPAGE_VAR_SABNZBD_URL: ENC[AES256_GCM,data:lIee1dG//COegfQ2c+7vi7jH1oBx4dk=,iv:YdRhTUwWNXlD8MCkEBgQX1jmU2tIzvX8VcfneUQxRkg=,tag:NIftwcslEjrX5mwytQcfhA==,type:str]
    HOMEPAGE_VAR_SABNZBD_KEY: ENC[AES256_GCM,data:d5tupnCCHkqQp1e/9mfu5mHtOt1769JcBfP1GbAGseQ=,iv:rxg8crWdmUpFzRhs4QDCdVKwb+fV+zx0l7BN14DmNrQ=,tag:my7oNEF4HMI+KDqKc4aIBg==,type:str]
    HOMEPAGE_VAR_SABNZBD_HREF: ENC[AES256_GCM,data:46st17rbEMFKCSLahZYRdkh8NNz8oVc=,iv:tDXi0MH7C74a41Qp8SURrdQB4qiiolOArfYWWXVNEgU=,tag:x4TmDVdNf/kPOWJIstGwvg==,type:str]
    HOMEPAGE_VAR_HOMEASSISTANT_URL: ENC[AES256_GCM,data:virv17m3kWqznrhzaQqEQAKggWPlu5A=,iv:gYhGQjJyYSvnt/HQttiJw3buwXgEWSWKRMMjySk95No=,tag:QMe40iTc+AMjPxXxh6O/Wg==,type:str]
    HOMEPAGE_VAR_HOMEASSISTANT_KEY: ENC[AES256_GCM,data:e9qKM5e0k5dgaOket6qoFRRDrs8nVwPMZCkodIN5srCaUkqT5mREo+amYrbEMLK9hxmAQ6tK/s5lCeJ+9TV+2fFznJRuxPPhbjlarDn8pnKf9Ny+a0Kbn42jN+5hYBeJT5TqLlXjoTUDx3mmGsVbIv/sVurr9ETlwePxRe1oMnv6DJhDmKjhBsaLreii66wKNTiQrlzN5CgwxYVyyHzx3KUS/wKUY1dzWU0gOFeO8j3E+X6Kt/Dx,iv:hrRYGKpNJ+sC5bAt6bUkW/GePsaiPFVSnOVs2yW9ABw=,tag:TM2yUDitogSxP2oGeAzvkg==,type:str]
    HOMEPAGE_VAR_HOMEASSISTANT_HREF: ENC[AES256_GCM,data:bQJ8q4Od+wCorRT3/8RC6/ZhanU=,iv:3dTVlErtWgsguV08WHiH3pMFi1dO+XltNJwdUqZFssQ=,tag:m9cuhQGJiP07qKidbBRRhw==,type:str]
    HOMEPAGE_VAR_FRIGATE_URL: ENC[AES256_GCM,data:7h5E6xK4YM2Oskhqdn6mTV5Cih6446I=,iv:n3CYwhtVTrKO+De2G8zVXAI5BkkSSnMrfZugo+rssoY=,tag:xbNsWRdPdq3JeiDN/NyQ4A==,type:str]
    HOMEPAGE_VAR_FRIGATE_KEY: ""
    HOMEPAGE_VAR_FRIGATE_HREF: ENC[AES256_GCM,data:vXStD0poz7O+DmtSxhqdDvV6AQI=,iv:VxHflaCG4T6m9LOZ+CpLyeII59tUFPIiOk/7zOIW6x4=,tag:P05LknngrtLlAGtPl92lfA==,type:str]
    HOMEPAGE_VAR_SONARR_URL: ENC[AES256_GCM,data:jbi73D/bxjtylVntrrgrDgSL1pkp3cE=,iv:KuGs4teb5PSBqI3ocwYmKYNiwpwhQhxFDIx9wGi6Abo=,tag:xbgno1bTf1lUbw1gml5AmQ==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:UtjriqUE709SSUBjdNf/NRv+KXtW4IUG4cJm9WiJjwc=,iv:F8UQXaoWbsOq4ynZRGlPkaDh1t20wL5hokwEHpLma2s=,tag:NaCJThiiehddBR27C8yudA==,type:str]
    HOMEPAGE_VAR_SONARR_HREF: ENC[AES256_GCM,data:gOvdwCEi4nphjLzM5CSlBiluc4S8TA==,iv:gw1wkKituenno1vdCQPwk5IpluxGFQML91r8R0LnZbs=,tag:stBZOYrwYAX0EzXZlB+R4Q==,type:str]
    HOMEPAGE_VAR_RADARR_URL: ENC[AES256_GCM,data:0yTdBrIt1aoeUFIIdYi74ksohizIz3A=,iv:ffOFeAnITG+yGz5IyzbmR6p11OZCCRGbn1XYjB+bw4A=,tag:2ZHuWmOcIUnwvJqUeg0/Fg==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:V9zsbAzVR49UcV8xwbuCUevjJj3BZ7Mbp+WTs5/94co=,iv:ALI0NED9I+lGhflLzR1KXUca59ZUC2EqxQp6HryrOWk=,tag:DoGyUExmyOY11KJcAEuF1g==,type:str]
    HOMEPAGE_VAR_RADARR_HREF: ENC[AES256_GCM,data:2rq30lTLxIXhpPw1nZ4ckUCAxqXzvg==,iv:BWd2ryqfeTphoz1/bT86TreswPr8Lg5fbEFCax3ZwOU=,tag:YdgG3NXi8TTCgJwkK/ixZQ==,type:str]
    HOMEPAGE_VAR_PROWLARR_URL: ENC[AES256_GCM,data:lBUmLYVyvdaa0lqArLaRtxFyr63mNxI=,iv:IFxrukFBIPozsj42jYt4bTtGEb4wfjW/+wyukTcLxbo=,tag:17yxwd6M+EEWXsUIKcExuA==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:VTCKreZ0miRoISwuhE1TPf+qo6VXFF3OA7MwZ9UC81k=,iv:436fZn32z2CFFyzWDaMbtl6qkNp1jdFAlZZ5lPuFE1E=,tag:kkP/jeH8uJxNUcGMSlCTrg==,type:str]
    HOMEPAGE_VAR_PROWLARR_HREF: ENC[AES256_GCM,data:HX+HLRVqb275uy8zLCNmAmr8byus9H7X,iv:oK9U9YyNPZ1rT7vYHLObYtCf7RdINH8GIVpXoWvzqCY=,tag:hshQD5zg31N05aqMR2HvkQ==,type:str]
    HOMEPAGE_VAR_PLEX_URL: ENC[AES256_GCM,data:OxyZcp11Q9ebCvmPNAuQGk7TXh1iH7x8,iv:a5Jtlpo81Ub6hYdszb8Xar5gtBPZyEVvaf4RgGndQOw=,tag:JH1euhtibHCKBlNVgs/lfA==,type:str]
    HOMEPAGE_VAR_PLEX_KEY: ENC[AES256_GCM,data:X5ExzFMZuImzEtpFM0PEcdWuDIE=,iv:9XoXvqvwEPnLMpQ5VONcHUejt2LsOA5fx0AkK8EYPUQ=,tag:y82QYww4XLyQWXhg97d+dg==,type:str]
    HOMEPAGE_VAR_PLEX_HREF: ENC[AES256_GCM,data:zI4lGjwIdT+q7NXsJCczPe7N5AA=,iv:Hlzhg2mPf9UkfKmXa2NinzOvO+paSg8+rIdHX4dQ5mM=,tag:11KTiZNQI5rytNQaA0U7/Q==,type:str]
    HOMEPAGE_VAR_JELLYFIN_URL: ENC[AES256_GCM,data:Otlg6lnXgPNLKYwm9ZJQd1PT4E3FHjs=,iv:gdFw2/xQ3Ft9U7NmyepAAM1DlocxNleVbR32ftIObfo=,tag:vDQCxSuYE8dFBVcEx8D3hw==,type:str]
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:oX6IbbCFSodWWsfcBGmwhTXGHye8fdILsoBRXbIvogA=,iv:IRFl7B1TzQ9bz3GQC7Gnszx3PAftHlNsvXsbOK0/s3g=,tag:jTdxGxX51q3k/vxmKrIN1A==,type:str]
    HOMEPAGE_VAR_JELLYFIN_HREF: ENC[AES256_GCM,data:qO9ojbKAv3p4F28pOIZHOqRAvZMsr3Zg,iv:Sl2BWq8ko9E/nyO6xOUJbRx2xtq8bbyYPm+1crsZ3bQ=,tag:qWiYv8OriJHVPOpOcIGb9A==,type:str]
    HOMEPAGE_VAR_IMMICH_URL: ENC[AES256_GCM,data:64a9QXLXaUKO8fsH65zA6KXW7xeWRks=,iv:uCQtFqkSVK5Fkajq+3ccI3zoP2ko/Gl/BPRnno6hxAM=,tag:qWdcS/WQYFXU6oeY1225iA==,type:str]
    HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:cgonMMNlcfnPvBIjrBJgkUhN1EI4X8rRhQz5Cya7Kh2CHCFn89rx36tF,iv:p1ILKrsian8897HeLqv24Di9iY3XIi8hQyn9R6y2M8Q=,tag:GxOlWfVW60YxfCfDmnFaUw==,type:str]
    HOMEPAGE_VAR_IMMICH_HREF: ENC[AES256_GCM,data:gJyD1dKfT/AJ0os+FOMFGPJquGz7UQ==,iv:5xqv/TueZWsxQNLdgFVyS+AkOzSzXm8/0F/Pvp115r8=,tag:5O225tY+ZlMrNaSNVfkngQ==,type:str]
    HOMEPAGE_VAR_LOGO: ENC[AES256_GCM,data:OUwBWNk65Tt1IF60G7y2BSWl/vdE/FMFXK7r3bLkHw==,iv:XxmJ1S06AgVKuUcEKlQNYMLJpttqJHw8D6m1Ij3Vkbc=,tag:peSUe+hFV15CF5MjUkJsCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0V0FLS0UrZXc1QmZXWU0r
            UnBLWmw0R0cyZ0IxOUJMMVlYZ3RVRGM5b1Q4CmthM2pueTNEMHFreFgreTVMVytk
            R1dEUGVKS0tzRDllT1VrQkJwK3pwcVkKLS0tIHE2amFwSUhLd3hCRkZlTzZhcU9V
            TEhJU051eDMzaVBwRHFlL3NSNjlxVzgKEJuSPruUK7Aqf8yRx/mBuaPvLm+nvX0t
            0XIx9LAxpiUl66yxcL2P0fQ6vUh5vGKHZgaNjI8HrF8kNzjm9rA3bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-14T13:09:58Z"
    mac: ENC[AES256_GCM,data:EH5sxcns9PQkRNFje7geehuhJrRMOkYtqgjw00zoYkSB7sABMWf4SKQIFJ1tl0ampl80lyUk3CJXoVeQ3A1eA32qck078hlZUk5Vt0C9vS3L3dGn9sYL5B+mdRhY86tzm1TMzWFqf1a0PgQUDUciTRRRyZL3oALxQGY4xVFKu/4=,iv:pE3sKp3WOO4cJe2/hEBjrmtYDtMfbBfg3O4NI7RaqUs=,tag:VQWrLejeYa6lV4FRbcJEeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: fc04a9956372f7c7582761c9072ddd9457d716bee3fff5786d830cf54a81f482
