kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgresql-secret
    namespace: postgresql
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:WqvY85H8XyUGpgb0zBER7a55HLU5HiiV8AcoTjWni8oFT6BBZYqu2w==,iv:WJvmR6C/DDkbVJjlepSYbcicOzh1kxrJZC83XBCXJV4=,tag:GW+RYUUfcoIIliSLogPC8A==,type:str]
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:9bEbH2SMbRBlTv5/+Q==,iv:DY6PMu6t76QSrYELTWAxTXfHRKvlPYj2OXgftIwUMWk=,tag:YkQxLA14itRaNoH104pEMQ==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:4w5jh4AlVZ0=,iv:U7BqOzWGlRPzzDNCUyGzqc1OYlcePX/2Yy81xDMSzYM=,tag:7d8ALMx5f2/EL9bm+YVkvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZXczdTZid05WZ0RhMlha
            bkFRaWdad2V1QVZPOENxcWRUTnpacE1mL3hRCnU0V25uci8zNnlEMGJJdHh0Tmhx
            RWtMcVpZWmpGK05tVktINmZJSmRXbkkKLS0tIGpPRjlDY3EweU9WUUZPL0E0QUw2
            dHUwcDlUNkpOeVhoUUdJSVJ1NnREbVUK2hT1GQqXXKt7fdfpI3Hetd7JBRPVgTZ8
            3xFCBn3XOkST1zM+Za1of4Fa4CMdTa0p8ctL+FEDPiaW5BuZOm8L0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-14T13:09:58Z"
    mac: ENC[AES256_GCM,data:sf4JOYt0I8QDeWEzSLOQ51sZ4RdqZ+rut1a/z3Vg2BDom9B4RGZrE54NXc6iu+227p7MZ04qhLxZJ2xCiHMKVRMjuBcoMiuhRH3IJyubBvLZHGC8RieHmiI+4IawRJKBqcnWFIfn89/4v5WLUtdvsgtSG4+e9DLYRZbm/7Tii8Q=,iv:opoAY5MOHhy/1MU2W9uaLpJiOdWrZFtxX1ToZauqKd8=,tag:K5IWmkL74arYJHG9WjWMYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: b84f2560f1998cd63005938bae046f8d31c2b854e9e0aa88bb7f0744bddc44ae
