apiVersion: v1
kind: Secret
metadata:
    name: gamesmanager-secret
    namespace: webdev
stringData:
    APP_BACKEND_AUTH: ENC[AES256_GCM,data:ti5QiVBcyyZu/Sp+yWpIRnMaaL+LS5ohXnH4mYedD0TIti6z4aFk,iv:tYM8u7MxWgkzt8oaxtglgseEVAU2nM6PbVSDqHawa3E=,tag:PFva4OeBfvYEuRPA7xvbdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0nhr3qkvuf7sr60sk89p4g29dksqz3k66sttlrkp68fkud38qdse3gqgt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzb1pLN3dXeG5LNitHUjBs
            UmN2NXRnU3Fyb3NlQnVNckRSSG44Q0tQVFRBCkZpREFXcCtvMDc3djZIV1hqOTV6
            TGtQdjAwRS9VYVBtTFhTYytpRkY1c0kKLS0tIGdjdTdOY3M2a3FsK204ekVWeWli
            ZTM0TklHakxMSUdWUTRRL3A4L250TzQKMzbVV1oskNI6xnjMfVvFmExtWO3noHMn
            IbeQBYxwRtpGivvXkXVGn6p2VIFihgkjlbkNSc/Eq3Qy69EE6+ewUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-20T14:04:36Z"
    mac: ENC[AES256_GCM,data:oO5rhVzkpDDI8xgElLahHgZ+MxDsz0EIvPK3Zm8N3yR5v06VEu02m1IySTdrTFhBr/oWjwZ2NkurXF0L6VKwiw+4DaLIKbpVP1GT85vhyoN2ttFuVaQCgWZJdkd7NfAfIwN/fI6tkivugOc3iQr3SRXIoSqi1xBkeUhh7HqkyJo=,iv:4yRDEwtSBtZFWHM4NbQFyWY/m02NHV18xj2Vqij0B1M=,tag:ypbg4fNfXF3LApm0y4hHTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
# Hash: f22f6ca94128e420af0e88a07b8f9ae7a5287ef46d2e758b62d4d85edafca8b3
