apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 30m
  chart:
    spec:
      chart: rancher
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: cattle-system
      interval: 12h 
  values:
    hostname: rancher.f9.casa
    ingress:
      tls:
        secretName: f9-casa-tls